apiVersion: apps/v1 
kind: Deployment
metadata:
  name: vmapp
  labels: 
     app: vmapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: vmapp

  template:
    metadata:
      labels:
        app: vmapp
    spec:
      containers:
      - name: vmapp
        image: us-east1-docker.pkg.dev/xenon-chain-407805/vm/appweb:V3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
